presubmits:
  - name: pre-watsonx-openai-shim-verify
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic-labs/watsonx-openai-shim.git"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.27-node-24-2
          command:
            - ./hack/ci/verify.sh
          resources:
            requests:
              memory: 2Gi
              cpu: 2
          env:
            - name: GOPROXY
              value: "http://athens-proxy.athens.svc.cluster.local,direct"

postsubmits: []
